### ISSUE TITLE
Connect to and read data from gps

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#199] opened 2015-09-28 04:23 UTC

**Comment by TrevorDecker** [comment] 2015-10-04 12:08
data has been read, still needs to be made reliable.

**Comment by VasuAgrawal** [comment] 2015-10-24 05:39
We should be able to continually read data from the GPS now. AFAIK the issue previously was caused by improperly pulling numbers out of the stream, but that's since been fixed and is upstream.

Closing.

**Closed** 2015-10-26 08:06 UTC
Labels: high-level (java)
